application: org-tom-wx-hrd
version: 1
#runtime: python27
runtime: python
api_version: 1
#threadsafe: true

handlers:

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /conditions.*
  script: main_handler.py

- url: /delete_archive.*
  script: delete_archive_handler.py
  login: admin

- url: /clean_cache.*
  script: clean_cache_handler.py
  login: admin
  
- url: /store_forecast.*
  script: wunderground_forecast_handler.py
  login: admin
  
- url: /test.*
  login: admin
  script: gaeunit.py

# catch-all
- url: .*
  script: main_handler.py

builtins:
- datastore_admin: on
#- appstats: on
- remote_api: on
