# app specific settings
# from memcache: app, namespace='config'
#  w = wunderground.Wunderground('KMABEVER3', 'password', 3.0)

locations:
  01915:
    # this is for translating incoming condition posts in the proper TZ on the web page
    tz: America/New_York
    post: True
    upload: True
    forecast_location: KBVY
    conditions_location: KBVY
    wunderground:
      station: KMABEVER3
      password: password
      conditions: True
      archives: True
  01915-dev:
    # this is for translating incoming condition posts in the proper TZ on the web page
    tz: America/New_York
    post: True
    upload: True
#    wunderground:
#      station: KMABEVER3
#      password: password
#      conditions: True
#      archives: True
    forecast_location: KBVY
    conditions_location: KBVY
  WARING:
    tz: America/New_York
    forecast_location: KBVY
    conditions_location: KBVY
    
